Update t.yml

diff --git a/.github/workflows/t.yml b/.github/workflows/t.yml
--- a/.github/workflows/t.yml
+++ b/.github/workflows/t.yml
@@ -1,8 +1,8 @@
-name: Update Telecom IPs
+name: Update huoq
 
 on:
   schedule:
-    - cron: "37 4 * * *"  # 每10分钟跑一次
+    - cron: "38 */3 * * *"  # 每10分钟跑一次
   workflow_dispatch:
 
 jobs:
@@ -13,22 +13,30 @@ jobs:
 
       - name: Install dependencies
         run: |
-          pip install playwright requests
-          playwright install chromium
+              pip install requests pandas
 
-      - name: Run script
+     
+
+      - name: Make script executable
+        run: chmod +x CloudflareST
+
+      - name: cstest
         env:
-          TARGET_URL: ${{ secrets.TARGET_URL }}
-          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
-          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
-          CF_RECORD_NAME: ${{ secrets.CF_RECORD_NAME }}
-        run: python ad.py
-      - name: Clean up Workflow Runs
-        uses: Mattraks/delete-workflow-runs@v2
-        with:
-         #token: ${{ secrets.GITHUB_TOKEN }}
-         token: ${{ secrets.PAT_TOKEN }}
+         TEST_URL: ${{ secrets.TEST_URL }}  # 如果是敏感数据，使用 secrets.TEST_URL
+         CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
+         CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
+         CF_RECORD_NAME: ${{ secrets.CF_RECORD_NAME }}
+        run: |
+          set -e
+          ./CloudflareST -f ip.txt -t 8 -p 0 -sl 1 -n 300  -dt 10 -tp 2087 -tlr 0 -url $TEST_URL
+          
+            python huoqdn.py
+      #- name: Clean up Workflow Runs
+       # uses: Mattraks/delete-workflow-runs@v2
+       # with:
+        # #token: ${{ secrets.GITHUB_TOKEN }}
+        # token: ${{ secrets.PAT_TOKEN }}
          
-         repository: ${{ github.repository }}
-         retain_days: 1
-         keep_minimum_runs: 0
+        # repository: ${{ github.repository }}
+       #  retain_days: 1
+        # keep_minimum_runs: 0
